name: static-analysis
run-name: Run CodeQL analysis

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-static-analysis
  cancel-in-progress: true

jobs:
  codeql:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python, javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
